### ISSUE TITLE
Nextjs 8

### ISSUE THREAD

**Issue by mataide** [gurkerl83/next-i18next-serverless#3]
I am having some issues while running under nextjs 8.
As my project cant update yet to nextjs 9.
I'd like to ask if this library works with nextjs 8?

**Comment by gurkerl83** [comment]
Hi, features like sever-less / lambda are available in Next since version 8. Since then, countless problems and open questions regarding server-less / lambda have arisen, especially in the integration of server-full libraries, which have increasingly been addressed by Next lately. The attempt available in this repository requires Next to be at least version v9.2.2-canary.10. The most important feature are runtimeConfigs, which are only available in Next in server-less mode from this version on. Next 8 is not supported.
